### ISSUE TITLE
Actividad 2. Conversiones

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-alan-ivan#2]
[Actividad 2. Conversiones de los sistemas numericos.pdf](https://github.com/user-attachments/files/16841696/Actividad.2.Conversiones.de.los.sistemas.numericos.pdf)

**Comment by LeinnaMora** [comment]
Portada: 25/25
Procedimiento: 22/25
Figuras, Ilustraciones y Fotografías: 20/25
Resultados y Conclusiones: 25/25
Calificación Final: 18.4/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
