### ISSUE TITLE
Practica 2. operación de conjuntos 

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-alan-ivan#3]
[Practica 2. Conjuntos.pdf](https://github.com/user-attachments/files/17123322/Practica.2.Conjuntos.pdf)

**Comment by Fidel20-01** [comment]
Portada:22/25
Procedimiento:22/25
Figuras, ilustraciones y fotografías:17/25
Resultados y conclusiones:17/25
78/100
Calificación: 15.6/20
Nota: Falto lista de Figuras, Nombre del profesor, faltaron mas imágenes y la conclusión era pequeña.
Evaluó: Equipo de Juan Pablo C.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
